<center><h1> Numpy Assignemnt </h1></center>

### Write the Code in empty cells to produce it's exact below output

## Import Numpy

In [2]:
import numpy as np

## Creating 3 Arrays (1-D, 2-D, 3-D)

In [4]:
arr= np.array([1,3,7,4])
arr

array([1, 3, 7, 4])

In [5]:
arr2=np.array([[1,2,3],[4,4,9]])
arr2

array([[1, 2, 3],
       [4, 4, 9]])

In [6]:
arr3= np.array([[[ 1,  3,  5],
                 [ 4,  9, 10],
                 [ 5,  3,  2]],
                 [[ 4,  6, 10],
                 [ 5,  9,  8],
                 [10,  3,  4]]])
arr3

array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])

## Use attributes of Numpy (ndim, shape, size, dtype, itemsize) for all above 3 arrays

In [8]:
print("Dimesion a array is :",arr.ndim)
print("Shape of array is :",arr.shape)
print("Size of Array is:",arr.size)
print("data type of array is:",arr.dtype)
print("itemsize of array :",arr.itemsize)

Dimesion a array is : 1
Shape of array is : (4,)
Size of Array is: 4
data type of array is: int32
itemsize of array : 4


In [9]:
print("Dimesion a array is :",arr2.ndim)
print("Shape of array is :",arr2.shape)
print("Size of Array is:",arr2.size)
print("data type of array is:",arr2.dtype)
print("itemsize of array :",arr2.itemsize)

Dimesion a array is : 2
Shape of array is : (2, 3)
Size of Array is: 6
data type of array is: int32
itemsize of array : 4


In [10]:
print("Dimesion a array is :",arr3.ndim)
print("Shape of array is :",arr3.shape)
print("Size of Array is:",arr3.size)
print("data type of array is:",arr3.dtype)
print("itemsize of array :",arr3.itemsize)

Dimesion a array is : 3
Shape of array is : (2, 3, 3)
Size of Array is: 18
data type of array is: int32
itemsize of array : 4


## Create Range Arrays

In [167]:
# This matrix (5x5) will have elements within the range of 0-99 with step size of 4


In [20]:
new_array=np.arange(0,120,4)
print("elemnts without shaping",new_array)
new_array1=new_array.reshape(5,6)
new_array1

elemnts without shaping [  0   4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68
  72  76  80  84  88  92  96 100 104 108 112 116]


array([[  0,   4,   8,  12,  16,  20],
       [ 24,  28,  32,  36,  40,  44],
       [ 48,  52,  56,  60,  64,  68],
       [ 72,  76,  80,  84,  88,  92],
       [ 96, 100, 104, 108, 112, 116]])

## Creating a Random array within range of 0-50

In [169]:
# This Matrix (4x6) will have random integers within range 0-50


In [21]:
new_array2=np.random.randint(0,51,(4,6))
new_array2

array([[48, 37, 46, 45, 28, 47],
       [ 1,  9, 14,  5,  9, 16],
       [24, 34, 47, 43, 44, 32],
       [40, 43, 21, 42, 33, 46]])

## Creating a Random array within range of 0.0 and 1.0 (Float)

In [22]:
# This 2x3 Matrix will have the float range from 0.0 to 1.0


In [23]:
new_array2=np.random.uniform(0.0,1.0,(2,3))
new_array2

array([[0.47902178, 0.69103561, 0.31030373],
       [0.1550747 , 0.58572096, 0.56846803]])

## Array Indexing

In [24]:
# Create the follwing array
arrn=np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arrn

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [25]:
## Return Unique Elements in the array
np.unique(arrn)

array([ 3,  5,  8, 12, 13, 15, 22, 25, 26, 30, 31, 34, 37, 38, 40, 41, 42,
       46, 48, 49])

In [26]:
# Return the First Row (Indexing starts with 0)
arrn[0]

array([15, 42, 41, 38, 49,  3])

In [27]:
# Return 3rd Row 3rd Element (Indexing starts with 0)
arrn[2,2]

12

In [28]:
# Returns 1st Row 4th Element (Indexing starts with 0)
arrn[0,3]

38

In [29]:
# Create the follwoing array
arr_r=np.arange(18)
r=arr_r.reshape(2,3,3)
r

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [30]:
# Return 1st array
r[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [180]:
# Returns 1st array 2nd row 3rd element
r[0,1,2]

5

## Array Slicing

<h4> <b> Slicing 1-Dimensional Arrays </b> </h4>

In [31]:
# Create the 1-Dimensional array 
array_s=np.array([1,5,7,4])
array_s

array([1, 5, 7, 4])

In [32]:
# Produce the follwing Result
array_s[2:4]

array([7, 4])

<h4> <b> Slicing 2-Dimensional Arrays </b> </h4>

In [33]:
# Create the 2-Dimensional array 
arr_ss=np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arr_ss

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [34]:
# Produce the follwoing result
arr_ss[:,1:3]

array([[42, 41],
       [ 8, 25],
       [22, 12],
       [30, 46]])

In [35]:
# Produce the follwoing result
arr_ss[0:3,0:3]

array([[15, 42, 41],
       [13,  8, 25],
       [34, 22, 12]])

In [36]:
# Produce the following result
arr_ss[1:3,3:5]

array([[25, 48],
       [37, 26]])

## Assigning Values to Arrays (Broadcasting)

<h4> <b> 1-Dimensional Arrays Broadcasting </b> </h4>

In [37]:
# Create 1-D Array
arr_rr=np.array([1,5,7,4])
arr_rr

array([1, 5, 7, 4])

In [38]:
# Change Index 3 value to 99
arr_rr[3]=99
arr_rr

array([ 1,  5,  7, 99])

In [39]:
# Change the Index vales by slicing
arr_rr[1:]=888
arr_rr

array([  1, 888, 888, 888])

<h4> <b> 2-Dimensional Arrays Broadcasting </b> </h4>

In [40]:
# Create the 2-D Array
arr_rrr=np.array([[1,2,3],[4,6,9]])
arr_rrr

array([[1, 2, 3],
       [4, 6, 9]])

In [41]:
# Change 1st row 2nd value 2 to 100
arr_rrr[0,1]=100
arr_rrr

array([[  1, 100,   3],
       [  4,   6,   9]])

In [42]:
# Change values by slicing the matrix and produce the follwoing results


## Numpy Operations

<h4> <b> Arithmetic Operations </b> </h4>

In [43]:
# Create the follwoing array
array_xyz=np.array([1,4,3,2,6,9])
array_xyz

array([1, 4, 3, 2, 6, 9])

In [44]:
# Add +10 to each element
array_xyzy=array_xyz+10
array_xyzy

array([11, 14, 13, 12, 16, 19])

In [45]:
# Subtract -10 from each element
array_xyzy=array_xyzy-10
array_xyzy

array([1, 4, 3, 2, 6, 9])

In [46]:
# Multiplying each element with 9
array_xyzy=array_xyz*9
array_xyzy

array([ 9, 36, 27, 18, 54, 81])

In [47]:
# Dividing each element with 2
array_xyzy=array_xyz/2
array_xyzy

array([0.5, 2. , 1.5, 1. , 3. , 4.5])

<h4> <b> Statistical Operations </b> </h4>

In [48]:
# Creating a New Array
array_qwe=np.arange(0,12)
array_qwe
xyz=array_qwe.reshape(3,4)
xyz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
# Sum Operations
# Produce total sum, row wise sum (first elements), columns wise sum
total_sum=xyz.sum()
print(total_sum)
rows_sum=xyz.sum(axis=1)
print(rows_sum)
col_sum=xyz.sum(axis=0)
print(col_sum)

66
[ 6 22 38]
[12 15 18 21]


In [50]:
# Calculate Mean, Meadian, Square root, minimum, maximum values of new_arr
x=np.mean(array_qwe)
"mean",x

('mean', 5.5)

In [51]:
xcv=np.median(array_qwe)
xcv

5.5

In [52]:
ycv=np.sqrt(array_qwe)
ycv

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [53]:
rjv=np.min(array_qwe)
rjv

0

In [54]:
rj=np.max(array_qwe)
rj

11